
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elcrqksvfrqtfdmmaowu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsY3Jxa3N2ZnJxdGZkbW1hb3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MDAzNzMsImV4cCI6MjA2MDM3NjM3M30.MGN7T0zcz5JiVbzhbHqamT40AOEvbBtp7zCJHPX_X58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Helper function to get typed access to tables
export const from = <T extends keyof Database['public']['Tables']>(
  table: T
) => supabase.from<Database['public']['Tables'][T]['Row']>(table);
